#include <stdio.h>

void main(){

while (1) {
  printf("                      ,dlc:;.\n");
  printf("                     .,;lkOx,\n");
  printf("                     .,,cxkd'\n");
  printf("                     ,c;cccl'\n");
  printf("                   ..',:ol;.\n");
  printf("                  .....,lko.\n");
  printf("                '::'..,,;dxl.\n");
  printf("             .';:;,'..,:;:dxl:,.....\n");
  printf("             ,c,:c:,..,::;:odddoooddl.\n");
  printf("              .;:oc,'':llclddd:',,cko.\n");
  printf("               ';::,,:dkdl:,,,.   .,,.\n");
  printf("               ':',;:oOOdo:..\n");
  printf("               :d,,:clddk00Odc,\n");
  printf("               ,l,;:ccc:coxk00Od:,\n");
  printf("              .;;;:cccc;.,::cldxxd,\n");
  printf("             .:;,::ccc,   ,:;;;cdd'\n");
  printf("        ..,,,cc;;::;,.       .,lxd'\n");
  printf(" ..,c:,;ccclooc::c,          .,:od,\n");
  printf(":dxoc:;;;;;;:cc;'.           ';,co'\n");
  printf("ldoc:;''',.....              .',cd,\n");
  printf("lll;.                         .;cxd,..  \n");
  usleep(200000);
  system("clear");
  printf("                      .'cxc.\n");
  printf("                      .:cdOo'\n");
  printf("                     .,';dOxo'\n");
  printf("                      ';:ccll.\n");
  printf("                   .lc;:oo;'.\n");
  printf("                  ':;,';dkl.\n");
  printf("                  ',..',dko;\n");
  printf("                ';;'..',lkoo'\n");
  printf("               .:::,..,,:oxxo:,....\n");
  printf("               .:co:.':cc:cloddddodc.\n");
  printf("                ,:;;,:dkdl:'',:llooc.\n");
  printf("                ':,;:oOOoo'    ....\n");
  printf("                .;';:lxkxko,\n");
  printf("                .;',:codk00ko.\n");
  printf("                ':,,::lc:lk00x;.\n");
  printf("   .::cc,...   .::,;::cl:;:cdkko.\n");
  printf("  ,cddxollll:;lxd:,;:clc'',;:cdd,\n");
  printf(".:oc:,;lc:;;:ccodl::cco'   .:cxd'\n");
  printf(",d:.. ......'',;;::ccl;    .;:dd'\n");
  printf(" .             ..;,,,;.    ':;co;\n");
  printf("                           .:::od,\n");
  printf("                            'c:ox;\n");
  printf("                            .::lxdc.,\n");
  printf("                            .cccloddx,\n");
  usleep(200000);
  system("clear");
  printf("                       .''''.\n");
  printf("                      .:clxx:\n");
  printf("                      .;,lOOd'\n");
  printf("                      .;,cllo'\n");
  printf("                    .';:ll:::. \n");
  printf("                   .c;':xxo,\n");
  printf("                  .''.,dOxo;\n");
  printf("                  ,,..;xxoll'\n");
  printf("                 ;:'..:xxlcl'\n");
  printf("                .:;'.';cddd:.\n");
  printf("                 .;,,;llcldxo:,. \n");
  printf("                .;;;:oOOo;:lddxxl.\n");
  printf("                .;',:lOOd;.':looo'\n");
  printf("                .,'',;okkx:  ',,'.\n");
  printf("         ....    .,'.,:oxkkc.\n");
  printf("       ,ldxkxl;'..,;'',cokOk:\n");
  printf("     .clccccc::cllool:;:lldkx;\n");
  printf("    .;,'.....,:c;::llllclccodx;\n");
  printf("              ...'.,;;::cccol:. \n");
  printf("                    ..';::odo'\n");
  printf("                       'c;clo'\n");
  printf("                       'c;:lc.\n");
  printf("                       'l:cd,\n");
  printf("                       'lcoxo,\n");
  printf("                       'lccoddl:.\n");
  printf("                       ,ollloooc.\n");
  usleep(200000);
  system("clear");
  printf("                        .''.\n");
  printf("                      .;,lxo,\n");
  printf("                      .,,lOOx'\n");
  printf("                      .;,:ooo'\n");
  printf("                   .'';:cl:,:.\n");
  printf("                   'l:;oxol'\n");
  printf("                  .,,:dkdoo;\n");
  printf("                  'cldxlclll'\n");
  printf("                .ccokko:ccc:.\n");
  printf("                .;::coxoccl'\n");
  printf("                 .;,';lxolx;\n");
  printf("                .;;;:codddoc:,\n");
  printf("                .;',:lkkddoclo:.\n");
  printf("                .''.',:oddol:;:.\n");
  printf("             ..  .,'..';coxx:\n");
  printf("            :dxo:,,;,,,,,:oxxl.\n");
  printf("          .lodddlcc:::ccclloxxo.\n");
  printf("         .colll:'.,:;;;;:cccldd,\n");
  printf("          ;oc'.   .loc:;::ccc:,. \n");
  printf("           .      ;c:cllll;..\n");
  printf("                 'l:;cll,\n");
  printf("                .cc::cc,\n");
  printf("                'l::llc.\n");
  printf("               .cllodd,\n");
  printf("               'lccoddl:;.\n");
  printf("               'l:;:clodd,\n");
  usleep(200000);
  system("clear");
  printf("                      ';''',.\n");
  printf("                      'ccdkk:\n");
  printf("                     .,';dOko.\n");
  printf("                     .;;:cclc.\n");
  printf("                    .;lcolc;.\n");
  printf("                  ':cldxdod,\n");
  printf("                ':oxkxoccoo;\n");
  printf("              .:cdxlc:;:clld,\n");
  printf("               ';dk:'',:ccc;.\n");
  printf("               .,:do;,;clcll,..\n");
  printf("                .,cooloxdccclcc;;:.\n");
  printf("                .,,cdxOOdl:,,;::cl'\n");
  printf("                .,';cokkOOko::'...\n");
  printf("                ':'',,;:coxkOko.,\n");
  printf("                'c,;ccc:;,;:ldkkxo.\n");
  printf("                'c,:lodolc::codddd,\n");
  printf("                'c,:clllc:::ccc:::\n");
  printf("               .llccc::;;;::,'...\n");
  printf("              ':lloolccl:...\n");
  printf("            .:cclloooo;.\n");
  printf("           .:c;:ccodd:\n");
  printf("          'cc::c:;;;:.\n");
  printf("        'colllc'\n");
  printf("        ;lclod,\n");
  printf("         .:odx:.\n");
  printf("          'ooddx,\n");
  usleep(200000);
  system("clear");
  printf("                       ;lo:.\n");
  printf("                      .;lkOo.\n");
  printf("                     .,':xkxc.\n");
  printf("                     ,l;cc:ld,\n");
  printf("                  ...;lool,.\n");
  printf("                .:ldoddood;\n");
  printf("             .,:oddlc:;;ldo'\n");
  printf("             .;okd:,.';:ccc'\n");
  printf("             ,c:xkl,.',:ccc:;'..,;:,\n");
  printf("             .;:okc''':llc;,;;:;,;:o,\n");
  printf("               ,ldl,,:dkdc;'....,,:;.\n");
  printf("               .cdo::lkOxdl,\n");
  printf("               ;dcc;;:lodxkOkdc,\n");
  printf("               :o,,,,,,,;;:loxkkko:.\n");
  printf("               ';;cllc:,.';,,;;cdxd,\n");
  printf("              ':;:clcc,   ..::;cdo:.\n");
  printf("            .,:;;:c:,'     'l::loo'\n");
  printf("         ';cooc;::;.      .cc;:co:.\n");
  printf("       'clccllc:;.        ;l:;:l;\n");
  printf("    .,clc:;:c;;'         :ol::ll.\n");
  printf("  .coolccc:,'           'oollod:\n");
  printf("  .:clloc'              .coooxxxl,.\n");
  printf("   'lod:                  .,cddddd,\n");
  usleep(200000);
  system("clear");
  printf("                      ;xc::.            \n");
  printf("                     .,;lkOo.           \n");
  printf("                     .,'cxkd,           \n");
  printf("                     'c;cc:l'           \n");
  printf("                ...',:ldoc;,.           \n");
  printf("               'cdddoodood:             \n");
  printf("             .:oddoc:;;:ldo'            \n");
  printf("             .:dko:'.';:ccc'     .'.    \n");
  printf("             .:lkxc,.',:ccc;,,,',col.   \n");
  printf("              ':dxl,.':llc;,;;::;;::.   \n");
  printf("               'odc,;:dkdl,........     \n");
  printf("               .odc;cokOxdl,.           \n");
  printf("               .::,,;;coxkOOko,.        \n");
  printf("               .:,;,,,,,;:codkkko:,     \n");
  printf("              .:;:clccc;,:;;;:coxxx,    \n");
  printf("             'l:;:ccc:'. .,:':c;lxd'    \n");
  printf("      ..,;,;;cc;:cc;'.       ;l;lxd'    \n");
  printf(" ,clc;cl::clol:;:l;          .;,:oo'    \n");
  printf(".loooc::;;;c;...''            .,;cl'    \n");
  printf(".'ll:;;.....                 .'':l'    \n");
  printf(":lo;.                          .,;o:.   \n");
  printf(":ol.                           .;;oxdc,,\n");
  printf(" ..                             ':coooc; \n");
  usleep(200000);
  system("clear");
  printf("                      .':xc.            \n");
  printf("                     .:ccxOd'           \n");
  printf("                     ,l';dOxo'          \n");
  printf("                      ';:ccll.          \n");
  printf("                  .,,:clol,'.           \n");
  printf("                 'lddddxdoc.            \n");
  printf("               'codxkdc:cdo;.           \n");
  printf("              'loxd:,,;:cclc.           \n");
  printf("              'ccxx;.',:ccc;.           \n");
  printf("              .;:ld:'';llccol;;,;:,.    \n");
  printf("               .;col:cdkdc:ccc:;:cl.    \n");
  printf("                'ccdxxOOdoc....,,.      \n");
  printf("                .;:ododkOOx:            \n");
  printf("                .:,,,,,:oxOOo,          \n");
  printf("      ..        'c;:cc:,,;cdkko'        \n");
  printf("    'ldxl,......;:;cooooc;;;cdkd:.      \n");
  printf("   ;olodolcccloxdc;cllo:..',;:oxd'      \n");
  printf(" .clloc,,:c:;;:loc:clld;   ,l;lxd,      \n");
  printf(" .;,''.  .....'.',;:cl:.   'c;cdd,      \n");
  printf("                 .....     'l;:lo'      \n");
  printf("                           .;:;:l'      \n");
  printf("                            .:;:l:.     \n");
  printf("                             .::oxl'.   \n");
  printf("                             'c:oxxool. \n");
  usleep(200000);
  system("clear");
  printf("                       .''''.           \n");
  printf("                      .cclxx:           \n");
  printf("                      .;,lOOd'          \n");
  printf("                      .;,cllo'          \n");
  printf("                    .';cll:::.          \n");
  printf("                   ,c:cdxol;            \n");
  printf("                  ;lcokxooo;            \n");
  printf("                 ;loxxocclll'           \n");
  printf("                'ccxOd::cccl'           \n");
  printf("                .::ldxocccl'            \n");
  printf("                 ':,,cdxold:..          \n");
  printf("                .;,;:coxdllllol.        \n");
  printf("                .;';:lodxxoc:cll.       \n");
  printf("                .,'.',:llod;';'.        \n");
  printf("         ,::,.   .:'..';cdxo.           \n");
  printf("      .,looxxl;;;';:,'',;cdxl.          \n");
  printf("     .:ollc:cc::cloooc;;;;cdd:.         \n");
  printf("     .:,,.. .';;:,;clc:cc:;cdd,         \n");
  printf("               ..';;c:;;cc:loo'         \n");
  printf("                    ..':c::oo;          \n");
  printf("                       'c;:ll'          \n");
  printf("                       'c;;co'          \n");
  printf("                       .c:;co,          \n");
  printf("                       'l::od:          \n");
  printf("                       'lcldxdc:.       \n");
  printf("                       'lcloddod,        \n");
  usleep(200000);
  system("clear");
  printf("                        .''.            \n");
  printf("                      .;,lxo,           \n");
  printf("                      .,,lOOx'          \n");
  printf("                      .;,:ooo'          \n");
  printf("                   ..,;:cl:,:.          \n");
  printf("                   'l:,cxdl'            \n");
  printf("                  .,'';xkdo;            \n");
  printf("                  .,''lkdlll'           \n");
  printf("                  ''.,okocc:.           \n");
  printf("                 .;'.':dxol'            \n");
  printf("                 .:,',:cldxo,.          \n");
  printf("                .;;;:lkklcodxoc.        \n");
  printf("                .;';:oOOdooloddl.       \n");
  printf("                .''',:okkxxl;coc.       \n");
  printf("             ... .,'.':oxOOo,.'.        \n");
  printf("            :dxxl::;'',coxOOx:          \n");
  printf("          .looodolc;,'':lloxkx:.        \n");
  printf("         .coooc,,,',c:,;cc:clol.        \n");
  printf("          ';;'     .:c;;cl:,'.          \n");
  printf("                  ':cccll:.             \n");
  printf("                 'l:;:cll'              \n");
  printf("                 ;c;;:co;               \n");
  printf("                'l;;;:l:                \n");
  printf("               .cc;:ll:.                \n");
  printf("               'lcldxdol;               \n");
  printf("               'lcldxxdool.             \n");
  usleep(200000);
  system("clear");
}}